# NumPy and ndarrays

In [1]:
import numpy as np

In [6]:
data = np.random.randn(2, 3)

In [7]:
data

array([[-1.74751872, -0.78649637, -0.16617807],
       [ 0.88278367, -0.05745125, -0.6486053 ]])

In [8]:
data * 100

array([[-174.75187233,  -78.64963702,  -16.61780659],
       [  88.27836724,   -5.74512455,  -64.86053035]])

In [9]:
data + data

array([[-3.49503745, -1.57299274, -0.33235613],
       [ 1.76556734, -0.11490249, -1.29721061]])

In [11]:
data.shape

(2, 3)

In [13]:
data.dtype

dtype('float64')

In [15]:
listy = [6, 7.5, 8, 1, 12]

In [16]:
arrayy = np.array(listy)

In [17]:
arrayy

array([ 6. ,  7.5,  8. ,  1. , 12. ])

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.empty((5, 5))

array([[1.49166815e-154, 1.49166815e-154, 8.39911598e-323,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 1.49166815e-154],
       [1.49166815e-154, 1.49166815e-154, 1.49166815e-154,
        4.44659081e-323, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 1.49166815e-154,
        1.49166815e-154, 2.96439388e-323]])

In [39]:
f = np.zeros((3, 3, 3))
f

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [40]:
g = np.arange(10)
g

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
g[5:8] = 69
g

array([ 0,  1,  2,  3,  4, 69, 69, 69,  8,  9])

In [42]:
gslice = g[4:9]

In [43]:
gslice[1] = 159
gslice

array([  4, 159,  69,  69,   8])

In [44]:
g

array([  0,   1,   2,   3,   4, 159,  69,  69,   8,   9])

In [23]:
a = np.zeros((3, 3, 3))

In [30]:
b = np.full_like(a, 77, dtype=np.int32)

In [31]:
b.dtype

dtype('int32')

In [35]:
b = b.astype(np.float64)

In [36]:
b.dtype

dtype('float64')

In [37]:
arr1 = np.array([[0., 4., 5.], [1., 2., 6.]])

arr2 = np.array([[1., 2., 6.], [0., 4., 5.]])

arr1 > arr2

array([[False,  True, False],
       [ True, False,  True]])

In [45]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
arr2d[:2, :1]

array([[1],
       [4]])

In [49]:
arr2d[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
arr2d[1:, 1:]

array([[5, 6],
       [8, 9]])

In [58]:
arr2d[1, 2]

6

In [61]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [63]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [65]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# Swapping axis: #

In [69]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [75]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [77]:
x = np.random.randn(8)
x

array([ 0.32210092, -0.09230704, -0.98127195, -1.79323628, -1.85880862,
        0.46638518,  1.72906415,  1.10285647])

In [78]:
y = np.random.randn(8)
y

array([ 1.3454833 ,  0.17021641, -0.64686688, -1.60213883, -0.09916144,
       -1.31294097,  2.12587626, -2.27202935])

In [79]:
np.maximum(x, y)

array([ 1.3454833 ,  0.17021641, -0.64686688, -1.60213883, -0.09916144,
        0.46638518,  2.12587626,  1.10285647])

In [83]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [84]:
cond = np.array([True, False, True, True, False])

# To take the value from xarr when the corresponding condition is True, 
# and from yarr when the corresponding value is False:

In [86]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

# This function is innately Boolean and does not require a separate Boolean array to work:

In [87]:
arr = np.random.randn(4, 4)
arr

array([[-0.06972449, -0.18442013,  0.5577682 , -1.37601065],
       [ 0.11938517, -0.43387139,  0.75297085, -0.02780594],
       [ 0.6795265 , -0.67825822, -0.2227705 ,  2.51591829],
       [ 1.27171353,  2.12468321,  0.39052401, -0.6341924 ]])

In [88]:
np.where(arr > 0, 2, -2)

array([[-2, -2,  2, -2],
       [ 2, -2,  2, -2],
       [ 2, -2, -2,  2],
       [ 2,  2,  2, -2]])

In [90]:
np.where(arr > 0, 2, arr)

array([[-0.06972449, -0.18442013,  2.        , -1.37601065],
       [ 2.        , -0.43387139,  2.        , -0.02780594],
       [ 2.        , -0.67825822, -0.2227705 ,  2.        ],
       [ 2.        ,  2.        ,  2.        , -0.6341924 ]])

In [93]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [94]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [95]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

In [97]:
np.min(arr)

0

In [98]:
np.max(arr)

8

In [99]:
np.var(arr)

6.666666666666667

In [100]:
np.std(arr)

2.581988897471611

# Using 'sum' as a way to count True values in a boolean array:

In [101]:
arr = np.random.randn(100)

In [102]:
(arr > 0).sum()

52

In [104]:
arr = np.random.randn(10)
arr

array([ 0.94673447, -0.62500569,  0.40072465,  1.45868245,  0.92387297,
        0.48131433,  0.13305492, -3.08337931,  1.58799321,  0.31045548])

In [105]:
arr.sort()

In [106]:
arr

array([-3.08337931, -0.62500569,  0.13305492,  0.31045548,  0.40072465,
        0.48131433,  0.92387297,  0.94673447,  1.45868245,  1.58799321])

In [107]:
arr = np.random.randn(5, 3)
arr

array([[ 0.90564689,  0.76569866,  0.26513281],
       [-1.1048502 ,  0.04887695,  0.24362331],
       [ 0.47945189, -0.75958566,  1.47577094],
       [ 0.15223716,  0.20129085, -0.58462295],
       [-1.70287587, -0.09304149, -0.51873401]])

In [112]:
arr.sort(1)
arr

array([[-1.70287587, -0.51873401, -0.09304149],
       [-1.1048502 ,  0.04887695,  0.20129085],
       [-0.75958566,  0.15223716,  0.24362331],
       [-0.58462295,  0.47945189,  0.90564689],
       [ 0.26513281,  0.76569866,  1.47577094]])

In [113]:
## Quantile computation:

In [114]:
large_arr = np.random.randn(1000)

In [115]:
large_arr.sort()

In [116]:
large_arr[int(0.1 * len(large_arr))] # 10% quantile

-1.3080907499976764

In [117]:
## Function testing membership of values in an array and returning
## a separate Boolean array:

In [118]:
values = np.array([6, 0, 0, 3, 2, 5, 6])

In [119]:
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

In [120]:
## Saving and loading data onto disk:

In [121]:
arr = np.arange(10)

In [122]:
np.save('some_array', arr)

In [123]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
## Matrix multiplication:

In [125]:
x = np.array([[1, 2, 3], [4, 5, 6]])

In [126]:
y = np.array([[6, 23], [-1, 7], [8, 9]])

In [127]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [130]:
y

array([[ 6, 23],
       [-1,  7],
       [ 8,  9]])

In [138]:
x.dot(y)

array([[ 28,  64],
       [ 67, 181]])

In [149]:
np.random.randint(10)

4

In [150]:
nsteps = 1000

In [151]:
draws = np.random.randint(0, 2, size = nsteps)

In [153]:
steps = np.where(draws > 0, 1, -1)

In [155]:
walk = steps.cumsum()

In [157]:
walk.min()

-1

In [159]:
walk.max()

48

In [160]:
np.abs(walk) >= 15

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [162]:
# Returns the index of the largest value

In [161]:
(np.abs(walk) >= 10).argmax()

51

In [169]:
# Generating 5000 random walks:

In [164]:
nwalks = 5000

In [165]:
nsteps = 1000

In [166]:
draws = np.random.randint(0, 2, size=(nwalks, nsteps))

In [167]:
steps = np.where(draws > 0, 1, -1)

In [168]:
walks = steps.cumsum(1)
walks

array([[  1,   0,   1, ...,  20,  19,  20],
       [ -1,  -2,  -1, ..., -58, -57, -56],
       [  1,   0,  -1, ...,  10,   9,  10],
       ...,
       [ -1,   0,   1, ..., -40, -41, -40],
       [ -1,   0,  -1, ...,  48,  47,  46],
       [  1,   0,  -1, ...,  18,  17,  18]])

In [185]:
# computing the number of walks that exceed abs(30) steps:

In [179]:
hits30 = (np.abs(walks) >= 30).any(1)

In [180]:
hits30

array([ True,  True, False, ...,  True,  True,  True])

In [184]:
hits30.sum()

3394

In [187]:
# using this boolean array to select out the rows of walks that cross abs(30)
# then calling argmax across axis 1 to get the crossing times:

In [188]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(1)
crossing_times

array([191, 585, 921, ..., 615, 239, 687])

In [189]:
# finally, computing average minimum crossing time:

In [191]:
crossing_times.mean()

501.42251031231586

In [192]:
len(crossing_times)

3394

# PANDAS TIME BABY

In [196]:
# This is what a pandas series looks like:

In [193]:
import pandas as pd

In [194]:
obj = pd.Series([4, 7, -5, 3])

In [195]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [199]:
# unspecified index simply goes from 0 to len(obj)

In [197]:
obj.values

array([ 4,  7, -5,  3])

In [198]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [200]:
obj2 = pd.Series([4, 7, -5, 4], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    4
dtype: int64

In [201]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [202]:
obj2['a']

-5

In [204]:
obj2[['c', 'a', 'd']]

c    4
a   -5
d    4
dtype: int64

In [205]:
# index-value link is preserved when operations are performed on values:

In [206]:
obj2 * 2

d     8
b    14
a   -10
c     8
dtype: int64

In [208]:
'b' in obj2

True

In [210]:
# pandas series are similar to dicts. dicts to Series conversion:

In [211]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [212]:
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [215]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [216]:
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [218]:
# As no value for California was found, it appears as NaN = 'Not a Number'.
# In pandas, NaN essentially means 'NA' or 'Missing.'

In [219]:
# isnull and notnull detect missing data:

In [220]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [221]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [222]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [227]:
obj4.name  = 'population'

In [224]:
obj4.index.name = 'State'

In [225]:
obj4

State
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [231]:
# A Series Dataframe is like a rectangular table of data, and can be thought of as a
# dict of Series sharing the same index. A common means of creating a Dataframe is by
# creating a dict of equal-length lists or NumPy arrays:

In [233]:
data = {'State': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'], 
        'Year': [2000, 2001, 2002, 2001, 2002, 2003], 
        'Population': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [234]:
frame = pd.DataFrame(data)
frame

State  Year  Population
0    Ohio  2000         1.5
1    Ohio  2001         1.7
2    Ohio  2002         3.6
3  Nevada  2001         2.4
4  Nevada  2002         2.9
5  Nevada  2003         3.2

In [235]:
# Specifiying a sequence of columns will arrange the columns in that order:

In [236]:
pd.DataFrame(data, columns=['Year', 'State', 'Population'])

Year   State  Population
0  2000    Ohio         1.5
1  2001    Ohio         1.7
2  2002    Ohio         3.6
3  2001  Nevada         2.4
4  2002  Nevada         2.9
5  2003  Nevada         3.2

In [237]:
# Passing a column not contained in the original dict will yield NaN values:

In [243]:
frame2 = pd.DataFrame(data, columns=['Year', 'State', 'Population', 'Debt'], 
                      index=['Y', 'E', 'E', 'E', 'E', 'T'])

In [244]:
frame2

Year   State  Population Debt
Y  2000    Ohio         1.5  NaN
E  2001    Ohio         1.7  NaN
E  2002    Ohio         3.6  NaN
E  2001  Nevada         2.4  NaN
E  2002  Nevada         2.9  NaN
T  2003  Nevada         3.2  NaN

In [246]:
# Adding a new column of boolean values according to an existing column:

In [248]:
frame2['Eastern'] = frame2.State == 'Ohio'
frame2

Year   State  Population Debt  Eastern
Y  2000    Ohio         1.5  NaN     True
E  2001    Ohio         1.7  NaN     True
E  2002    Ohio         3.6  NaN     True
E  2001  Nevada         2.4  NaN    False
E  2002  Nevada         2.9  NaN    False
T  2003  Nevada         3.2  NaN    False

In [249]:
# And then deleting that bitch:

In [250]:
del frame2['Eastern']
frame2.columns

Index(['Year', 'State', 'Population', 'Debt'], dtype='object')

In [251]:
# In a nested dict of dicts that is passed to DataFrame, the outer keys will be interpreted
# as columns and the inner keys as row indices:

In [252]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9}, 
      'Ohio': {2000: 1.5, 2001: 1.7, 2002: 2.6}}

In [253]:
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 2.6}}

In [254]:
frame3 = pd.DataFrame(pop)

In [255]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   2.6
2000     NaN   1.5

In [256]:
# Transposing (swapping rows and columns):

In [257]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   2.6   1.5

In [260]:
pop = pd.DataFrame(pop, index=[2000, 2001, 2002, 2003])

In [261]:
pop

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   2.6
2003     NaN   NaN

In [263]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}

In [264]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   2.6     2.9

In [266]:
# Setting name attributes of index and columns:

In [269]:
frame2.index.name = 'Year'; frame2.columns.name = 'State'
frame2

State  Year   State  Population Debt
Year                                
Y      2000    Ohio         1.5  NaN
E      2001    Ohio         1.7  NaN
E      2002    Ohio         3.6  NaN
E      2001  Nevada         2.4  NaN
E      2002  Nevada         2.9  NaN
T      2003  Nevada         3.2  NaN

In [270]:
frame3.values

array([[2.4, 1.7],
       [2.9, 2.6],
       [nan, 1.5]])

In [271]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [272]:
# Index Objects:

In [273]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [275]:
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [276]:
index[1:]

Index(['b', 'c'], dtype='object')

In [277]:
# are immutable:

In [278]:
index[1] = 'b'

TypeError: Index does not support mutable operations

In [279]:
# making it safer to share indexes between data structures:

In [281]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [282]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [283]:
obj2.index is labels

True

In [285]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='State')

In [286]:
'Ohio' in frame3.columns

True

In [287]:
2003 in frame3.index

False

In [288]:
# indexes can contain duplicate labels:

In [289]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [297]:
dup_labels.delete(1)

Index(['foo', 'bar', 'bar'], dtype='object')

In [296]:
dup_labels.insert(1, 'Yeet')

Index(['foo', 'Yeet', 'foo', 'bar', 'bar'], dtype='object')

In [312]:
# reindex conforms data to a new index:

In [307]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [308]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [309]:
obj2['e'] = 7

In [310]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    7.0
dtype: float64

In [313]:
# interpolation (filling) of values while reindexing using the 'ffill' method option:

In [314]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index = [0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [315]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [316]:
# specify to reindex columns rather than rows:

In [317]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'], columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [318]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [319]:
states = ['Texas', 'Utah', 'California']

In [320]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [321]:
# removing entries from an axis using 'drop':

In [322]:
frame.drop('c')

Ohio  Texas  California
a     0      1           2
d     6      7           8

In [325]:
frame.drop(['a', 'd'])

Ohio  Texas  California
c     3      4           5

In [326]:
# again, performing this function on columns requires a specific call:

In [329]:
frame.drop('Texas', axis="columns")

Ohio  California
a     0           2
c     3           5
d     6           8

In [330]:
# to manipulate the object as it is without creating a new one, use 'inplace'
# NB - THIS WILL DESTROY THE DATA THAT IS DROPPED!

In [332]:
frame.drop('Ohio', axis='columns', inplace=True)

In [333]:
frame

Texas  California
a      1           2
c      4           5
d      7           8

In [334]:
# Series indexing is analagous to array indexing:

In [335]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [336]:
obj['b']

1.0

In [337]:
obj[1]

1.0

In [340]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [342]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [343]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [344]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [350]:
# Modifying section of Series = setting:
# NB - slicing with Series INCLUDES THE END-POINT

In [347]:
obj['b':'c'] = 3.3
obj

a    0.0
b    3.3
c    3.3
d    3.0
dtype: float64

In [352]:
# Indexing into a DataFrame to retrieve a column:

In [353]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'], columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [354]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [356]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [357]:
# row selection syntax:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [358]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [359]:
# bool:

In [360]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [362]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [363]:
# the loc and iloc commands allow selection of subsections of DataFrame rows AND columns:

In [365]:
data.loc['Colorado',['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [366]:
# iloc uses integers to index:

In [367]:
data.iloc[2, [1, 2, 3]]

two       9
three    10
four     11
Name: Utah, dtype: int64

In [368]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [369]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [370]:
# Both functions also work with slices:

In [371]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [384]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [386]:
# some other functions:

In [385]:
data.at['Colorado', 'four']

7

In [389]:
# try to use non-integer indexes to avoid ambiguity with data sets containing integers:

In [394]:
ser = pd.Series(np.arange(3.)) ## this sucks
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [402]:
# behaviour of Series addition:

In [396]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [397]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])


In [398]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [399]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [400]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [403]:
# and DataFrame addition:

In [408]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=['b', 'c', 'd'], 
                   index=['Ohio', 'Texas', 'Colorado'])

In [409]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [411]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'), 
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [412]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [413]:
# which yields the union of each df's indexes and columns:

In [414]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [415]:
# addition of DataFrames with no columns or rows in common will yield 
# a df with all null values

In [421]:
# the add method combined with a specified fill_value replaces null valuess:

In [418]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                  columns=list('abcd'))

In [419]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                  columns = list('abcde'))

In [423]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [425]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [427]:
# some other Series and DataFrame arithmetic methods:
# (beginning the method with r flips the subject!)

In [428]:
df1.div(df2)

a         b         c         d   e
0  NaN  1.000000  1.000000  1.000000 NaN
1  0.8  0.833333  0.857143  0.875000 NaN
2  0.8  0.818182  0.833333  0.846154 NaN
3  NaN       NaN       NaN       NaN NaN

In [429]:
df2.rdiv(df1)

a         b         c         d   e
0  NaN  1.000000  1.000000  1.000000 NaN
1  0.8  0.833333  0.857143  0.875000 NaN
2  0.8  0.818182  0.833333  0.846154 NaN
3  NaN       NaN       NaN       NaN NaN

In [430]:
df1.mul(df2)

a     b      c      d   e
0   0.0   1.0    4.0    9.0 NaN
1  20.0  30.0   42.0   56.0 NaN
2  80.0  99.0  120.0  143.0 NaN
3   NaN   NaN    NaN    NaN NaN

In [431]:
df2.mul(df1)

a     b      c      d   e
0   0.0   1.0    4.0    9.0 NaN
1  20.0  30.0   42.0   56.0 NaN
2  80.0  99.0  120.0  143.0 NaN
3   NaN   NaN    NaN    NaN NaN

In [432]:
# broadcasting involves operations between different sized data array
# in this example the smaller array performs an operation on all rows
# of the larger array:

In [434]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [435]:
arr1 = arr[0]
arr1

array([0., 1., 2., 3.])

In [436]:
arr - arr1

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [437]:
# similarly with operations between a DataFrame and a Series:

In [439]:
frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
                    columns=list('bde'),
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [440]:
series = frame.loc['Utah']
series

b    0
d    1
e    2
Name: Utah, dtype: int64

In [441]:
# arithmetic betwen the two matches the index of the series to the df's columns,
# broadcasting down the rows:

In [442]:
frame - series

b  d  e
Utah    0  0  0
Ohio    3  3  3
Texas   6  6  6
Oregon  9  9  9

In [443]:
# null behaviour:

In [444]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])

In [445]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [446]:
# specify axis to instead broadcast down the columns:

In [448]:
series3 = frame['d']
series3

Utah       1
Ohio       4
Texas      7
Oregon    10
Name: d, dtype: int64

In [449]:
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [453]:
frame.sub(series3, axis=0)

b  d  e
Utah   -1  0  1
Ohio   -1  0  1
Texas  -1  0  1
Oregon -1  0  1

In [455]:
# NumPy ufuncs also work on pandas objects:

In [456]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), 
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [457]:
frame

b         d         e
Utah    0.692975 -1.843232 -0.805582
Ohio   -0.259158 -2.295536  0.402891
Texas   0.108344  0.709729 -0.046825
Oregon  0.491246  0.996976 -0.632741

In [458]:
np.abs(frame)

b         d         e
Utah    0.692975  1.843232  0.805582
Ohio    0.259158  2.295536  0.402891
Texas   0.108344  0.709729  0.046825
Oregon  0.491246  0.996976  0.632741

In [459]:
# the following function 'f' computes the difference between the max
# and min values of a Series, invoked once on each column:

In [460]:
f = lambda x: x.max() - x.min()

In [461]:
frame.apply(f)

b    0.952133
d    3.292512
e    1.208473
dtype: float64

In [462]:
# passing 'axis=columns' will invoke the function on the rows:

In [463]:
frame.apply(f, axis='columns')

Utah      2.536206
Ohio      2.698427
Texas     0.756554
Oregon    1.629717
dtype: float64

In [464]:
# a function formatting to two decimal points:

In [470]:
format = lambda x: '%.2f' % x

In [471]:
frame.applymap(format)

b      d      e
Utah     0.69  -1.84  -0.81
Ohio    -0.26  -2.30   0.40
Texas    0.11   0.71  -0.05
Oregon   0.49   1.00  -0.63

In [473]:
# 'applymap' is distinct from 'map', a built-in series method
# for applying an element-wise function.

In [474]:
frame['e'].map(format)

Utah      -0.81
Ohio       0.40
Texas     -0.05
Oregon    -0.63
Name: e, dtype: object

In [475]:
# sorting and ranking datasets:

In [476]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

In [479]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [478]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [481]:
# with a DataFrame you can sort by either axis:

In [483]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                    index=['three', 'one'],
                    columns=['d', 'a', 'b', 'c'])

In [485]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [486]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [487]:
# and in descending order:

In [488]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [489]:
# and by its values:

In [490]:
obj = pd.Series([4, 7, -3, 2])

In [492]:
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [494]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [495]:
# missing values are sorted to the end by default:

In [496]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [497]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [498]:
# using column data as sort key:

In [500]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})

In [501]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [504]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [511]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4, 9, 8, 8])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
7    9
8    8
9    8
dtype: int64

In [513]:
# rank assigns ranks from one through the number of valid data points.
# rank breaks ties by assiging each gorup the mean rank:

In [512]:
obj.rank()

0     6.5
1     1.0
2     6.5
3     4.5
4     3.0
5     2.0
6     4.5
7    10.0
8     8.5
9     8.5
dtype: float64

In [514]:
# ranking according to the order in which they're observed:
obj.rank(method='first')

0     6.0
1     1.0
2     7.0
3     4.0
4     3.0
5     2.0
6     5.0
7    10.0
8     8.0
9     9.0
dtype: float64

In [515]:
# ranking can be done in descending order:

In [516]:
obj.rank(ascending=False, method='max')

0     5.0
1    10.0
2     5.0
3     7.0
4     8.0
5     9.0
6     7.0
7     1.0
8     3.0
9     3.0
dtype: float64

In [517]:
# and DataFrames can rank over rows or columns:

In [518]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1], 'c': [-2, 5, 8, -2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [520]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [521]:
# many pandas functions like reindex require all unique elements in the index,
# but this isn't mandatory:

In [522]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [523]:
obj.index.is_unique

False

In [524]:
# indexing a label with multiple entries returns a Series:

In [525]:
obj['a']

a    0
a    1
dtype: int64

In [527]:
obj['c']

4

In [528]:
# same logic applies with a DataFrame:

In [529]:
frame = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
frame

0         1         2
a -0.731355  1.056236 -1.745262
a -0.873247 -0.130206 -0.321615
b  0.118156  1.488352  1.203906
b  0.575335 -1.060520  0.132959

In [536]:
frame.loc['a']

0         1         2
a -0.731355  1.056236 -1.745262
a -0.873247 -0.130206 -0.321615

In [537]:
# pandas includes a number of mathematical methods that deal with missing data
# better than NumPy:

In [538]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]],
                 index=['a', 'b', 'c', 'd'], columns=['one', 'two'])

In [539]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [540]:
df.sum() # returns a Series:

one    9.25
two   -5.80
dtype: float64

In [543]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [544]:
# skipping of nan values can be disbaled with 'skipna':

In [545]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [546]:
# idxmax/idxmin returns index of max/min value:

In [547]:
df.idxmax()

one    b
two    d
dtype: object

In [548]:
# accumulation:

In [549]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [550]:
# 'describe' produces summary statistics for non-numeric data:

In [551]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)

In [552]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [557]:
df = pd.DataFrame([[1.4, 2.6], [7.1, 3.1], [1.5, 7.8], [0.75, 18.5]],
                 index=['a', 'b', 'c', 'd'], columns=['one', 'two'])
df

one   two
a  1.40   2.6
b  7.10   3.1
c  1.50   7.8
d  0.75  18.5

In [561]:
df = 100 * df.pct_change() # returns the % change between values:

In [ ]:
df.applymap(format)